baseURL = 'https://lemoe.cn/'
languageCode = 'zh-cn'
title = '柠萌赛博自留地'

timeout = '600s'
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"


[module.hugoVersion]
extended = true
min = "0.87.0"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  compact = false

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "twikoo"

    [params.comments.twikoo]


  [params.widgets]
  homepage = [ ]
  page = [ ]

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[markup.goldmark.renderer]
  unsafe= true