kind: pipeline
type: docker
name: Auto build

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    restore: true
    mount:
      - ./hugo/public

- name: Notion2Hugo
  image: node
  environment:
    NODE_ENV: CI
    NOTION_TOKEN:
      from_secret: NOTION_TOKEN
    NOTION_DB:
      from_secret: NOTION_DB
  commands:
  - node -v
  - npm -v
  - npm config set registry https://registry.npmmirror.com
  - yarn
  - npm install -g ts-node
  - ts-node src/main.ts

- name: Hugo-build
  image: klakegg/hugo:ext-alpine-ci
  commands:
  - cd hugo/public && git init && git remote add origin ssh://git@ssh.qmcmc.cn:222/qctech/notion2hugo.git && git fetch --all && git reset --hard origin/master 
  - cd ../ && hugo

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    rebuild: true
    mount:
      - ./hugo/public

- name: git-push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@git.qmcmc.cn:222/qctech/lemoe.cn.git
    force: true
    commit: true
    path: ./hugo/public
    author_name: build_bot
    author_email: me@lemoe.cn
    ssh_key:
      from_secret: SSH_KEY

volumes:
  - name: cache
    host:
      path: /tmp/lemoe.cn