kind: pipeline
type: docker
name: Auto build

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    restore: true
    mount:
      - ./hugo/content/post

- name: Notion2Hugo
  image: node
  environment:
    NODE_ENV: CI
    NOTION_TOKEN:
      from_secret: NOTION_TOKEN
    NOTION_DB:
      from_secret: NOTION_DB
  commands:
  - node -v
  - npm -v
  - npm config set registry https://registry.npmmirror.com
  - yarn
  - npm install -g ts-node --registry=https://registry.npmmirror.com
  - cd hugo
  - git clone https://git.qmcmc.cn/qctech/notion2hugo public
  - cd ../ && ts-node src/main.ts

- name: Hugo-build
  image: klakegg/hugo:ext-alpine-ci
  commands:
  - cd hugo && hugo
  # - git lfs install
  # - cd public && git lfs track "*.png"
  # - cd public && git lfs track "*.jpg"

- name: git-push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: ssh://git@git.qmcmc.cn:222/qctech/lemoe.cn.git
    force: true
    remote_name: master
    commit: true
    path: ./hugo/public
    author_name: build_bot
    author_email: bot@lemoe.cn
    ssh_key:
      from_secret: SSH_KEY

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    rebuild: true
    mount:
      - ./hugo/content/post


volumes:
  - name: cache
    host:
      path: /tmp/lemoe