name: Deploy Hugo site

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ./hugo/content/post
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Dependencies
        run: bun install

      - name: Notion to Hugo
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB: ${{ secrets.NOTION_DB }}
          NODE_ENV: CI
        run: |
          cd hugo
          git clone https://github.com/TennousuAthena/lemoe.cn public
          cd ../ && bun run src/main.ts

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo
        run: cd hugo && hugo

      - name: Deploy
        run: |
          cd hugo/public
          git config --global user.name "build_bot"
          git config --global user.email "bot@lemoe.cn"
          git add .
          git commit -m "Deploy by GitHub Actions"
          git push --force "https://${{ secrets.DEPLOY_TOKEN }}@git.qmcmc.cn/qctech/lemoe.cn.git" HEAD:master
